name = "fotodrop"
main = "./worker.js"
compatibility_date = "2026-05-03"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "fotodrop-db"
database_id = "4166aa4e-bd3e-402d-9990-3dbd0c2e6e66"

[[r2_buckets]]
binding = "DISPLAY_BUCKET"
bucket_name = "fotodeck-display"
