name = "fotodrop"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "fotodrop-local"
database_id = "local"

[[r2_buckets]]
binding = "DISPLAY_BUCKET"
bucket_name = "fotodrop-display-local"
